# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CIStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CISystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=255)),
                ('login', models.CharField(blank=True, max_length=255, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('change_ci_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('triggered_by', models.CharField(choices=[(b'Timer', b'Timer'), (b'Gerrit trigger', b'Gerrit trigger'), (b'Manual', b'Manual'), (b'Any', b'Any')], max_length=30, null=True)),
                ('gerrit_branch', models.CharField(max_length=255, null=True)),
                ('gerrit_refspec', models.CharField(max_length=255, null=True)),
                ('ci_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='cidashboard.CISystem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('build_id', models.IntegerField(null=True)),
                ('result', models.CharField(default=b'SKIPPED', max_length=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='cidashboard.Job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('jobs', models.ManyToManyField(to='cidashboard.Job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('jobs_results', models.ManyToManyField(to='cidashboard.JobResult')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='cidashboard.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('change_ci_status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('ci_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='cidashboard.CISystem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.ManyToManyField(to='cidashboard.View'),
        ),
        migrations.AddField(
            model_name='cistatus',
            name='ci_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='cidashboard.CISystem'),
        ),
        migrations.AddField(
            model_name='cistatus',
            name='jobs_results',
            field=models.ManyToManyField(to='cidashboard.JobResult'),
        ),
    ]
