# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cistatus',
            name='status',
            field=models.CharField(default='UNK', max_length=255),
            preserve_default=False,
        ),
    ]
